export enum Routes {
  AUTH = 'auth',
  USERS = 'users',
  POSTS = 'posts',
  CONVERSATIONS = 'conversations',
  CHAT = 'chat',
  FRIEND_REQUEST = 'friend-request',
  NOTIFICATIONS = 'notifications',
}

export enum Services {
  AUTH = 'AUTH_SERVICE',
  USERS = 'USERS_SERVICE',
  CONVERSATIONS = 'CONVERSATIONS_SERVICE',
  POSTS = 'POSTS_SERVICE',
  CHAT = 'CHAT_SERVICE',
  FRIEND_REQUEST = 'FRIEND_REQUEST_SERVICE',
  NOTIFICATION = 'NOTIFICATION_SERVICE',
  LIKES = 'LIKES_SERVICE',
  COMMENTS = 'COMMENTS_SERVICE',
  MENTIONS = 'MENTIONS_SERVICE',
  HASHTAGS = 'HASHTAGS_SERVICE',
}
